---
abstract: 'Subrouting Attributes for common POE tasks'
author:
  - 'M. Nunberg <mnunberg@hakalah.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Sugar-Attributes
no_index:
  directory:
    - t
    - inc
requires:
  Attribute::Handlers: 0.85
  Class::Struct: 0
  Constant::Generate: 0.03
  Log::Fu: 0.25
  POE: 0
  Test::More: 0
version: 0.02
